import {getTimeForZone,getDateForZone} from "./timezoneEngine.js";
const cities=[{city:"Lagos",zone:"Africa/Lagos"},{city:"London",zone:"Europe/London"},{city:"New York",zone:"America/New_York"},{city:"Tokyo",zone:"Asia/Tokyo"},{city:"Dubai",zone:"Asia/Dubai"},{city:"Sydney",zone:"Australia/Sydney"}];
const root=document.querySelector("#converter");
if(root){
root.innerHTML='<p class="eyebrow">TIME CONVERTER</p><h2>Compare a time</h2><p class="muted">Choose a city, date and time to compare locations.</p><div class="converter-form"><label>From city<select id="convert-from"></select></label><label>Date<input id="convert-date" type="date"></label><label>Time<input id="convert-time" type="time" step="60"></label><label>To city<select id="convert-to"></select></label></div><div class="converter-result" id="converter-result" aria-live="polite"></div><h3>Compare across cities</h3><div class="converter-grid" id="converter-grid"></div><p class="muted" id="converter-note"></p>';
const from=root.querySelector("#convert-from"),to=root.querySelector("#convert-to"),date=root.querySelector("#convert-date"),time=root.querySelector("#convert-time");
for(const city of cities){for(const select of [from,to]){const opt=document.createElement("option");opt.value=city.zone;opt.textContent=city.city;select.append(opt)}}
to.value="Europe/London";
function parts(zone,instant){const items=new Intl.DateTimeFormat("en-GB",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(instant);return Object.fromEntries(items.filter(p=>p.type!=="literal").map(p=>[p.type,Number(p.value)]))}
function wallMinutes(p){return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute)}
function resolve(zone,d,t){const [y,m,day]=d.split("-").map(Number),[h,min]=t.split(":").map(Number);if(!y||!m||!day||!Number.isInteger(h)||!Number.isInteger(min))return null;const target=Date.UTC(y,m-1,day,h,min);let matches=[];for(let offset=-840;offset<=840;offset+=15){const candidate=new Date(target-offset*60000);const p=parts(zone,candidate);if(wallMinutes(p)===target)matches.push(candidate)}matches.sort((a,b)=>a-b);return matches}
function update(){if(!date.value||!time.value)return;const matches=resolve(from.value,date.value,time.value),out=root.querySelector("#converter-result"),grid=root.querySelector("#converter-grid"),note=root.querySelector("#converter-note");grid.replaceChildren();if(!matches?.length){out.textContent="This local time does not exist in the selected city because of a daylight-saving transition.";note.textContent="Choose another time.";return}const instant=matches[0];const hour12=document.querySelector("#clock-format-12")?.getAttribute("aria-pressed")==="true";out.textContent=cities.find(c=>c.zone===from.value).city+" "+date.value+" "+time.value+" → "+cities.find(c=>c.zone===to.value).city+": "+getTimeForZone(to.value,instant,hour12)+" · "+getDateForZone(to.value,instant);for(const city of cities){const card=document.createElement("div");card.className="converter-city";const name=document.createElement("strong");name.textContent=city.city;const value=document.createElement("span");value.textContent=getTimeForZone(city.zone,instant,hour12)+" · "+getDateForZone(city.zone,instant);card.append(name,value);grid.append(card)}note.textContent=matches.length>1?"This time occurs twice due to daylight saving. Showing the first occurrence.":"Conversions account for each city's time zone and daylight saving."}
const now=new Date(),p=parts(from.value,now);date.value=[p.year,String(p.month).padStart(2,"0"),String(p.day).padStart(2,"0")].join("-");time.value=[p.hour,p.minute].map(v=>String(v).padStart(2,"0")).join(":");[from,to,date,time].forEach(el=>el.addEventListener("change",update));document.querySelectorAll("#clock-format-12,#clock-format-24").forEach(el=>el.addEventListener("click",()=>setTimeout(update,0)));update();
}
